### ISSUE TITLE
No build instructions

### ISSUE THREAD

**Issue by m4v** [dhmitry/keyboard-chatter-test#2]
If I clone the repository and run `npm dev run` in it I get:
```
> dev
> next dev

sh: 1: next: not found
```

If I use `yarn dev` I get:
```
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'dev'
```

I'm not familiar with the frameworks used, so I'm missing something.

This is in a Ubuntu 22.04 machine.

**Comment by dhmitry** [comment]
Did you run `npm install` first?

**Comment by m4v** [comment]
Thank you. That's what it was missing.
