### ISSUE TITLE
Please add the ability to change time detection for keys, i want to check if my keys chatter at speed 100ms or higher

### ISSUE THREAD

**Issue by Kalash004** [dhmitry/keyboard-chatter-test#4]
Please add the ability to change time detection for keys. 
I want to be able to check if my keys chatter at speed 100ms or higher.
Thanks :)

**Comment by dhmitry** [comment]
@Kalash004 is this still relevant for you? Haven't had much time to work on it, but should be able to work on it during the next few weeks.

**Comment by Kalash004** [comment]
In the end i had to buy a new keyboard XD.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
